# Generated by Django 5.2.5 on 2025-09-21 20:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hospital/Clinic Name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('subdomain', models.CharField(help_text='Subdomain for hospital (e.g., apollo.yourdomain.com)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Only lowercase letters, numbers, and hyphens allowed')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('working_hours', models.JSONField(default=dict, help_text='Working hours configuration')),
                ('subscription_plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('max_doctors', models.IntegerField(default=5, help_text='Maximum number of doctors allowed')),
                ('max_appointments_per_month', models.IntegerField(default=100)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('payment_gateway_enabled', models.BooleanField(default=False)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=100)),
                ('smtp_host', models.CharField(blank=True, max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Hospital Owner'), ('admin', 'Hospital Admin'), ('manager', 'Department Manager'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_users', to='tenants.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hospital', 'role', 'user'],
                'unique_together': {('hospital', 'user')},
            },
        ),
    ]
