# Generated by Django 5.2.5 on 2025-10-12 06:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='working_hours',
            field=models.JSONField(default=dict, help_text='Example: {"Monday": "9:00-17:00", "Tuesday": "9:00-17:00"}'),
        ),
    ]
