# Generated by Django 5.2.5 on 2025-09-21 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('guest_sessions', models.IntegerField(default=0)),
                ('user_sessions', models.IntegerField(default=0)),
                ('whatsapp_sessions', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('user_messages', models.IntegerField(default=0)),
                ('assistant_messages', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('avg_confidence_score', models.FloatField(default=0)),
                ('helpful_responses', models.IntegerField(default=0)),
                ('unhelpful_responses', models.IntegerField(default=0)),
                ('doctor_recommendations', models.IntegerField(default=0)),
                ('appointment_bookings', models.IntegerField(default=0)),
                ('hospital_inquiries', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Chat Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('example_phrases', models.JSONField(default=list, help_text='List of example user phrases')),
                ('keywords', models.JSONField(default=list, help_text='Keywords associated with this intent')),
                ('response_templates', models.JSONField(default=list, help_text='Template responses for this intent')),
                ('is_active', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['intent_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AlterModelOptions(
            name='whatsappsession',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('doctor_recommendation', 'Doctor Recommendation'), ('appointment_booking', 'Appointment Booking'), ('hospital_info', 'Hospital Information'), ('symptom_analysis', 'Symptom Analysis'), ('emergency_triage', 'Emergency Triage'), ('triage_followup', 'Triage Follow-up'), ('triage_update', 'Triage Update'), ('followup_answers', 'Follow-up Answers')], default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Time taken to generate response', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='structured_data',
            field=models.JSONField(default=dict, help_text='Structured data like doctor recommendations'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='context_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of conversation'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Optional email provided by guest', max_length=254),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='guest_identifier',
            field=models.CharField(blank=True, help_text='Browser fingerprint or IP for guests', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Optional name provided by guest', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='max_messages',
            field=models.IntegerField(default=100, help_text='Maximum messages to keep'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_preferences',
            field=models.JSONField(default=dict, help_text='User preferences and context'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='profile_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='whatsapp_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='context_days',
            field=models.IntegerField(default=10, help_text='Days to keep history for guests'),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappsession',
            unique_together={('hospital', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chatbot_cha_session_488328_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'message_type'], name='chatbot_cha_role_c389b5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chatbot_cha_session_9384e5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_cha_user_id_9fd70b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['guest_identifier', 'is_guest'], name='chatbot_cha_guest_i_81c20b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['expires_at'], name='chatbot_cha_expires_501b52_idx'),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='chatanalytics',
            unique_together={('hospital', 'date')},
        ),
    ]
