# Generated by Django 5.2.5 on 2025-10-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_fix_whatsapp_session'),
        ('tenants', '0002_alter_hospital_phone_alter_hospital_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.hospital'),
        ),
    ]
