# Generated by Django 5.2.5 on 2025-08-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("experience", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=20)),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("consultation_start", models.TimeField()),
                ("consultation_end", models.TimeField()),
                (
                    "consultation_days",
                    models.CharField(default="Mon-Sat", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.category",
                    ),
                ),
            ],
        ),
    ]
