# Generated by Django 5.2.5 on 2025-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="consultation_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="consultation_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
