# Generated by Django 5.2.5 on 2025-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_alter_doctor_consultation_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="consultation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
