# Generated by Django 5.2.5 on 2025-09-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_doctor_consultation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("zipcode", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.CharField(max_length=20)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.doctor",
                    ),
                ),
            ],
        ),
    ]
