# Generated by Django 5.2.5 on 2025-09-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0005_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_id",
            field=models.CharField(
                blank=True, editable=False, max_length=40, null=True, unique=True
            ),
        ),
    ]
