# Generated by Django 5.2.5 on 2025-09-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0006_appointment_appointment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
