# Generated by Django 5.2.6 on 2025-09-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_appointment_appointment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_date', 'appointment_time')},
        ),
    ]
