# Generated by Django 5.2.5 on 2025-10-15 15:50

import adminapp.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_manual_database_fix'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', validators=[adminapp.validators.validate_ten_digit_phone]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.category'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, help_text='Degrees, certifications, etc.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN', validators=[adminapp.validators.validate_ten_digit_phone]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(default='Dr.', max_length=20),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_start_time',
        ),
    ]
