# Generated by Django 5.2.5 on 2025-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appoi",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
