# Generated by Django 5.2.5 on 2025-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_appoi_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usertype", models.CharField(max_length=14)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
        ),
    ]
