# Generated by Django 5.2.5 on 2025-08-29 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_logininfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("contactno", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("profile", models.ImageField(null=True, upload_to="profiles/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "login",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.logininfo",
                    ),
                ),
            ],
        ),
    ]
