# Generated by Django 5.2.5 on 2025-09-21 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_enquiry'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.hospital'),
        ),
    ]
